"""add analysis pipeline tables and project ownership

Adds repo_snapshots, analysis_reports and skill_assessments, gives projects a
real foreign key to users, and moves the fetched repository fields off projects
onto repo_snapshots, where each analysis run keeps its own copy.

The backfill SQL is PostgreSQL-specific; tests build their schema from the
models rather than by running migrations.

Revision ID: 1579851acdd9
Revises: 02148f4a1a2d
Create Date: 2026-09-15 02:30:31.873081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1579851acdd9'
down_revision: Union[str, Sequence[str], None] = '02148f4a1a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=False),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('user_commit_count', sa.Integer(), nullable=True),
    sa.Column('readme_content', sa.Text(), nullable=True),
    sa.Column('file_tree', sa.JSON(), nullable=True),
    sa.Column('sampled_files', sa.JSON(), nullable=True),
    sa.Column('commit_history', sa.JSON(), nullable=True),
    sa.Column('contributor_stats', sa.JSON(), nullable=True),
    sa.Column('fetch_mode', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fetch_mode IN ('authenticated', 'public')", name=op.f('ck_repo_snapshots_fetch_mode')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_repo_snapshots_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repo_snapshots'))
    )
    op.create_index(op.f('ix_repo_snapshots_project_id'), 'repo_snapshots', ['project_id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo_snapshot_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('overall_trust_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('authorship_signals', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('attestation_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('attestation_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('attested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_status', sa.String(), server_default='none', nullable=False),
    sa.Column('anchored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bitcoin_block_height', sa.Integer(), nullable=True),
    sa.CheckConstraint("attestation_status IN ('pending', 'committed', 'mirrored', 'failed')", name=op.f('ck_analysis_reports_attestation_status')),
    sa.CheckConstraint("timestamp_status IN ('none', 'pending', 'anchored', 'failed')", name=op.f('ck_analysis_reports_timestamp_status')),
    sa.CheckConstraint('overall_trust_score BETWEEN 0 AND 100', name=op.f('ck_analysis_reports_overall_trust_score_range')),
    sa.ForeignKeyConstraint(['repo_snapshot_id'], ['repo_snapshots.id'], name=op.f('fk_analysis_reports_repo_snapshot_id_repo_snapshots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_reports')),
    sa.UniqueConstraint('repo_snapshot_id', name=op.f('uq_analysis_reports_repo_snapshot_id'))
    )
    op.create_index(op.f('ix_analysis_reports_content_hash'), 'analysis_reports', ['content_hash'], unique=False)
    op.create_table('skill_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=False),
    sa.Column('claimed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), server_default='[]', nullable=False),
    sa.CheckConstraint("level IN ('beginner', 'intermediate', 'advanced')", name=op.f('ck_skill_assessments_level')),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name=op.f('ck_skill_assessments_confidence_range')),
    sa.ForeignKeyConstraint(['report_id'], ['analysis_reports.id'], name=op.f('fk_skill_assessments_report_id_analysis_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_assessments')),
    sa.UniqueConstraint('report_id', 'skill_name', name=op.f('uq_skill_assessments_report_id_skill_name'))
    )
    # repo_owner and repo_name are NOT NULL, so they are added nullable, backfilled
    # from the submitted URL, then tightened. Adding them NOT NULL outright would
    # fail on any table that already holds rows.
    op.add_column('projects', sa.Column('repo_owner', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('repo_name', sa.String(), nullable=True))
    op.execute(
        r"""
        UPDATE projects
           SET repo_owner = split_part(
                   trim(both '/' from regexp_replace(github_repo_url, '^\w+://[^/]+/', '')), '/', 1),
               repo_name = regexp_replace(
                   split_part(
                       trim(both '/' from regexp_replace(github_repo_url, '^\w+://[^/]+/', '')), '/', 2),
                   '\.git$', '')
         WHERE repo_owner IS NULL
        """
    )
    op.alter_column('projects', 'repo_owner', existing_type=sa.String(), nullable=False)
    op.alter_column('projects', 'repo_name', existing_type=sa.String(), nullable=False)
    op.add_column('projects', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('visibility', sa.String(), server_default='private', nullable=False))
    # status was nullable with a Python-side default only, so rows written outside
    # the ORM could hold NULL.
    op.execute("UPDATE projects SET status = 'pending' WHERE status IS NULL")
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               server_default='pending',
               nullable=False)
    # Alembic does not autogenerate CHECK constraints on existing tables.
    op.create_check_constraint(
        'status', 'projects',
        "status IN ('pending', 'fetching', 'analyzing', 'attesting', 'completed', 'failed')")
    op.create_check_constraint('visibility', 'projects', "visibility IN ('private', 'public')")
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_projects_user_id_users'), 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'commit_count')
    op.drop_column('projects', 'readme_content')
    op.drop_column('projects', 'repo_languages')
    op.add_column('users', sa.Column('github_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_slug', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_unique_constraint(op.f('uq_users_profile_slug'), 'users', ['profile_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_profile_slug'), 'users', type_='unique')
    op.drop_column('users', 'profile_is_public')
    op.drop_column('users', 'profile_slug')
    op.drop_column('users', 'github_username')
    op.add_column('projects', sa.Column('repo_languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('readme_content', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('commit_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_projects_user_id_users'), 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_constraint(op.f('ck_projects_visibility'), 'projects', type_='check')
    op.drop_constraint(op.f('ck_projects_status'), 'projects', type_='check')
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    op.drop_column('projects', 'visibility')
    op.drop_column('projects', 'error_message')
    op.drop_column('projects', 'repo_name')
    op.drop_column('projects', 'repo_owner')
    op.drop_table('skill_assessments')
    op.drop_index(op.f('ix_analysis_reports_content_hash'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_repo_snapshots_project_id'), table_name='repo_snapshots')
    op.drop_table('repo_snapshots')
    # ### end Alembic commands ###
