"""baseline users and projects

Revision ID: 02148f4a1a2d
Revises: 
Create Date: 2026-09-15 02:15:45.234274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02148f4a1a2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('github_repo_url', sa.String(), nullable=False),
    sa.Column('live_demo_url', sa.String(), nullable=True),
    sa.Column('skills_claimed', sa.JSON(), nullable=True),
    sa.Column('role_in_project', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('repo_languages', sa.JSON(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('readme_content', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('github_id', sa.String(), nullable=True),
    sa.Column('github_access_token', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('github_id', name=op.f('uq_users_github_id')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
